import styles from './index.module.scss';
import Head from 'next/head';
import ReactFullpage from '@fullpage/react-fullpage';
import LinksContact from '../components/links-contact/links-contact';
import PageExperience from '../components/experience/experience';
import PageProfile from '../components/presentation/presentation';
import Topbar from '../components/topbar/topbar';
import { useTranslation } from 'react-i18next';

export default function Home() {
   const { t } = useTranslation();
   return (
      <>
         <Head>
            <title>dev. Bonilla</title>
            <meta charSet='utf-8' />
            <meta name='viewport' content='initial-scale=1.0, width=device-width' />
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/logo.svg' />
         </Head>
         <main className={styles.container}>
            <Topbar />
            <LinksContact />
            <ReactFullpage
               licenseKey={'C902507B-544140F0-99907E7D-AD3AE246'}
               scrollingSpeed={500}
               cards={false}
               cardsOptions={{ perspective: 100, fadeContent: true, fadeBackground: true }}
               render={() => {
                  return (
                     <ReactFullpage.Wrapper>
                        <div className='section'>
                           <PageProfile pImg='/pro-picture.jpg' />
                        </div>
                        <div className='section'>
                           <PageExperience
                              title='GLITCH'
                              essence={t('experience.essenceGlitch')}
                              pImg='/glitch.png'
                              link='https://glitchanimation.com/'
                           />
                        </div>
                        <div className='section'>
                           <PageExperience
                              title='SELEGO'
                              essence={t('experience.essenceSelego')}
                              pImg='/selego.png'
                              link='https://selego.com/'
                           />
                        </div>
                        <div className='section'>
                           <PageExperience
                              title='MYST'
                              essence={t('experience.essenceMyst')}
                              pImg='/myst.png'
                              link='https://themyst.com/'
                           />
                        </div>
                     </ReactFullpage.Wrapper>
                  );
               }}
            />
         </main>
      </>
   );
}
