import ReactFullpage from "@fullpage/react-fullpage";
import Head from "next/head";
import LinksContact from "../components/LinksContact";
import PageExperience from "../components/PageExperience";
import PageProfile from "../components/PageProfile";
import Topbar from "../components/Topbar";
import styles from "../styles/Main.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Boni Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Topbar />
      <LinksContact />
      <ReactFullpage
        //fullpage options
        licenseKey={"YOUR_KEY_HERE"}
        scrollingSpeed={1000} /* Options here */
        render={({ state, fullpageApi }) => {
          return (
            <ReactFullpage.Wrapper>
              <div className="section">
                <PageProfile
                  moveSection={() => fullpageApi.moveSectionDown()}
                  btnLabel="Preciona para bajar"
                  title="GLITCH"
                  pImg="/pro-picture.jpg"
                />
              </div>
              <div className="section">
                <PageExperience
                  moveSection={() => fullpageApi.moveSectionDown()}
                  btnLabel="Preciona para bajar"
                  title="GLITCH"
                  essence="Obras con un lenguaje visual único y contundente, capaz de deleitar a los aficionados a las artes gráficas: dibujo, ilustración, diseño gráfico, diseño de personajes, etc, y que además estén soportadas por una historia bien contada."
                  type="Website"
                  pImg="/glitch.png"
                />
              </div>
              <div className="section">
                <PageExperience
                  moveSection={() => fullpageApi.moveSectionDown()}
                  btnLabel="Preciona para bajar"
                  title="SELEGO"
                  essence="Cine y contenido independiente clásico y contemporáneo con un enfoque especial en la diversidad, la inclusión y la perspectiva de género, así como en el compromiso político y las narrativas experimentales."
                  type="Website"
                  pImg="/selego.png"
                />
              </div>
              <div className="section">
                <PageExperience
                  moveSection={() => fullpageApi.moveSectionUp()}
                  btnLabel="Preciona para subir"
                  title="MYST"
                  essence="Pequeña tienda de los horrores, busca todas las cosas misteriosas, desde la ficción criminal, pasando por el thriller y el terror, hasta el surrealismo más loco."
                  type="Website"
                  pImg="/myst.png"
                />
              </div>
            </ReactFullpage.Wrapper>
          );
        }}
      />
    </div>
  );
}
